### ISSUE TITLE
the npx pod-install-ios command

### ISSUE THREAD

**Issue by Prathamkrishna** [react-navigation/react-navigation.github.io#1022]
https://reactnavigation.org/docs/getting-started

the command which kinda worked for me is the npx pod-install rather than the mentioned npx pod-install-ios. 
I was having trouble getting everything linked in my project.

**Comment by kacperkapusciak** [comment]
Hi @Prathamkrishna :wave:
 
The docs states `npx pod-install ios` command without an additional dash between `install` and `ios` which works fine.

Cheers
