### ISSUE TITLE
Document RTL layout related concerns

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#104]
What limitations do we have around this?

**Comment by ramyareye** [comment]
Hi, I'm using it and it seems all ok :)
https://snack.expo.io/@ramyareye/3f385f
https://github.com/react-navigation/drawer/blob/master/example/src/RTLDrawer.tsx

I can manage it to have a rtl / ltr app to test all staff in action, if not you can close it maybe 👍
