### ISSUE TITLE
Broken Netlify pipeline due to unsupported build image

### ISSUE THREAD

**Issue by wirebug** [react-navigation/react-navigation.github.io#1080]
Hey there your deployment to Netlify fails with the following warning
```
UNSUPPORTED BUILD IMAGE

  The build image for this site uses Ubuntu 14.04 Trusty Tahr, which is no longer supported.

  To enable builds for this site, select a later build image at the following link:
  https://app.netlify.com/sites/react-navigation-docs/settings/deploys#build-image-selection

  For more details, visit the build image migration guide:
  https://answers.netlify.com/t/end-of-support-for-trusty-build-image-everything-you-need-to-know/39004
```
You can follow the migration guide to use Focal.

As this issue isn't related to the docs content it would be great to have some kind of marking for technical issues in the future. Maybe a label of some kind seem to be the right thing?

**Comment by eriveltonelias** [comment]
Hi there! Thanks for opening the issue, we're already addressed that fix a couple of weeks ago.
