### ISSUE TITLE
Suggested way to specifying default types for useNavigation, Link, ref etc. is against a recommended eslint rule

### ISSUE THREAD

**Issue by janschloss** [react-navigation/react-navigation.github.io#1086]
Hello,

in this document it is suggested to declare a module for specifying default types for useNavigation, Link, ref etc.:  https://github.com/react-navigation/react-navigation.github.io/blob/main/versioned_docs/version-6.x/typescript.md#specifying-default-types-for-usenavigation-link-ref-etc

However the eslint rule no-namespace which is part of the recommended rules for the TypeScript plugin disapproves of it: https://github.com/typescript-eslint/typescript-eslint/blob/v5.2.0/packages/eslint-plugin/docs/rules/no-namespace.md

**Comment by janschloss** [comment]
Is there any opinion on this?

**Comment by Adnan-Bacic** [comment]
while already on the topic of these types, it also gives an error for extending to an empty interface, referring to this rule:

https://github.com/typescript-eslint/typescript-eslint/blob/v5.2.0/packages/eslint-plugin/docs/rules/no-empty-interface.md

**Comment by satya164** [comment]
Linter warnings are about potential issues, and in this case purely code-style and not actual problems.
