### ISSUE TITLE
`IsSigned` in instead of `IsSignedIn` in auth-flow page

### ISSUE THREAD

**Issue by rafaeltab** [react-navigation/react-navigation.github.io#1095]
# Current Behavior
In the section `Don't manually navigate when conditionally rendering screens​` when referring to the `IsSignedIn` variable it was referred to as ``` `IsSigned` in   ```

# Expected Behavior
It should be referred to as ``` `IsSignedIn` ```

# Versions
| Version | Bug present |
|---------|-------------|
| 1.x     | ❌           |
| 2.x     | ❌           |
| 3.x     | ❌           |
| 4.x     | ❌           |
| 5.x     | ✔           |
| 6.x     | ✔           |

**Comment by eriveltonelias** [comment]
closing in favor of https://github.com/react-navigation/react-navigation.github.io/pull/1096
