### ISSUE TITLE
Documentation: Failed to open docs/redux-integration page

### ISSUE THREAD

**Issue by samwatkinson1** [react-navigation/react-navigation.github.io#1103]
### Current behavior

When attempting to navigate to https://reactnavigation.org/docs/redux-integration/, the following error occurs:
```js
DOMException: Failed to execute 'insertBefore' on 'Node': 
The node before which the new node is to be inserted is not a child of this node.
```
This seems to only happen when navigating to this specifc page.

### Expected behavior

The documentation page loads without error.

### Reproduction

https://reactnavigation.org/docs/redux-integration/

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| Chrome | 96.0.4664.45 |

**Comment by eriveltonelias** [comment]
Hey guys! This issue has been resolved, thanks!
