### ISSUE TITLE
Add Drawer Navigation Snack expo example

### ISSUE THREAD

**Issue by vikrantnegi** [react-navigation/react-navigation.github.io#114]
While going through the documentation I found that drawer navigation is lacking snack expo example, unlike other navigation. 
I know that it is obvious at that point on how to use the navigation but I think it would be of great help if there was a working example that we can edit on the fly.

Thanks.

**Comment by vickywane** [comment]
Here is a simple example demonstrating the drawer navigator. 
https://snack.expo.io/Bk2HvmE-N
