### ISSUE TITLE
Document search not working

### ISSUE THREAD

**Issue by miyataka** [react-navigation/react-navigation.github.io#1220]
Dear maintainers.

Document search is not working now. (2023-03-07)

![image](https://user-images.githubusercontent.com/15692588/223297034-d55d64d0-f872-4c98-8254-938a4c55da30.png)

![Screenshot 2023-03-07 at 10 40 48](https://user-images.githubusercontent.com/15692588/223297166-118cf93b-4214-4403-a2ae-71073fe6cf7a.png)

Please update API key.

Thanks.

**Comment by satya164** [comment]
Fixed

**Comment by miyataka** [comment]
thanks!
