### ISSUE TITLE
Found screens with the same name nested inside one another

### ISSUE THREAD

**Issue by hoanghcmus** [react-navigation/react-navigation.github.io#1258]
I am using `react-navigation 6`
I create a **HomeStack** : 
```const HomeStack = createNativeStackNavigator()```
I create **HomeNavigator**: 

``` 
const HomeNavigator = () => {
  return (
    <HomeStack.Navigator>
      <HomeStack.Screen name={ScreenTypes.Home} component={HomeScreen} />
    </HomeStack.Navigator>
```

I create another **RootNavigator** with include **HomeNavigator**: 
```
const RootNavigator = () => (
  <RootStack.Navigator
    screenOptions={{
      headerShown: false,
      animation: 'fade',
    }}
  >
    <RootStack.Screen name={ScreenTypes.Home} component={HomeNavigator} />
  </RootStack.Navigator>
)
```

When I run app, I got following warning issue 
```
Found screens with the same name nested inside one another. Check:

Home, Home > Home

This can cause confusing behavior during navigation. Consider using unique names for each screen instead. 
```

**Comment by Adil7767** [comment]
i am getting still this issue
and think due to this no images display on ios physical devices

**Comment by Adil7767** [comment]
i am getting still this issue
and think due to this no images display on ios physical devices

**Comment by satya164** [comment]
I believe the warning is self-explanatory. Please read the warning and fix the issue in your code.
