### ISSUE TITLE
Improve React-Navigation SVGs

### ISSUE THREAD

**Issue by RiteshK-611** [react-navigation/react-navigation.github.io#1270]
### Problem
All react-navigation SVGs are not optimized properly. And they have big file size of around 33 KB which is because these SVGs has many control points.
**SVG Files**
https://github.com/react-navigation/react-navigation.github.io/blob/main/static/img/spiro.svg
https://github.com/react-navigation/react-navigation.github.io/blob/main/static/img/spiro_header.svg
https://github.com/react-navigation/react-navigation.github.io/blob/main/static/img/spiro_white.svg

### Solution
This problem can be solve if we can reprocess the icon with curves rather than one-by-one control points.

**Comment by panditakshay402** [comment]
@RiteshK-611 can you assign this issue!
