### ISSUE TITLE
Custom navigators doc - addListener in child navigation

### ISSUE THREAD

**Issue by endoooo** [react-navigation/react-navigation.github.io#131]
in order to support StackNavigator and DrawerNavigator as sub-navigators of a custom navigator, we need to supply `addListener` to the childNavigation prop.

today, the documented example considers only state and dispatch:

``` js
// The state of the active child screen can be found at routes[index]
let childNavigation = { dispatch, state: routes[index] };
// If we want, we can also tinker with the dispatch function here, to limit
// or augment our children's actions
```

I'll send a pull request to fix this and prevent others to spend hours trying to figure out why the sub-navigators just won't work... 😬

**Comment by ericvicenti** [comment]
Thank you!
