### ISSUE TITLE
 Invariant Violation: ViewPagerAndroid has been removed from React Native. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native'. See https://github.com/callstack/react-native-viewpager

### ISSUE THREAD

**Issue by shubhext** [react-navigation/react-navigation.github.io#1340]
Getting the issue in only Android and in ios it is working

Invariant Violation: ViewPagerAndroid has been removed from React Native. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native'. See https://github.com/callstack/react-native-viewpager

This error is located at:
    in NavigationContainer (at App.tsx:210)
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)

  "react-navigation": "Snailapp/react-navigation#2.18.7",
  "react-native": "0.64.4",
  "react-native-gesture-handler": "1.10.3",
 "react-native-reanimated": "1.13.1",
  
<img width="284" alt="Screenshot 2024-04-27 at 1 41 38 PM" src="https://github.com/react-navigation/react-navigation.github.io/assets/113660511/da555a37-7b27-4018-ac6a-d0ca0bd8b611">
<img width="225" alt="Screenshot 2024-04-27 at 1 42 36 PM" src="https://github.com/react-navigation/react-navigation.github.io/assets/113660511/7f2d8caa-b666-40ab-99d9-53ad32bd64bc">

**Comment by satya164** [comment]
1. This repo is for documentation. Don't open bug reports here.
2. You're using an outdated version of react navigation which is no longer supported. Please migrate to the latest version https://reactnavigation.org/
