### ISSUE TITLE
Local install instructions are incomplete

### ISSUE THREAD

**Issue by maslade** [react-navigation/react-navigation.github.io#135]
When I followed the `README.md` to test local doc changes, I saw the homepage but clicking any links produced error pages like `Cannot GET /docs/getting-started.html`. I got it working by creating a `docs -> ../build/react-navigation-next.github.io/docs/` symlink under the `static` directory.

If that (symlinking/copying into `static`) is the correct way to do it, I can send over a PR to resolve this issue.

**Comment by brentvatne** [comment]
I followed the instructions from "Run it locally" on https://github.com/react-navigation/react-navigation.github.io

```
1. Clone the repository
2. cd into the website directory.
3. Run yarn (or npm install)
4. yarn start
```

<img width="731" alt="screen shot 2018-04-30 at 11 56 57 am" src="https://user-images.githubusercontent.com/90494/39444749-9c0e2870-4c6d-11e8-921f-4cb303cfeaa8.png">

it worked as expected. can you re-create issue with more info?
