### ISSUE TITLE
`beforeRemove` actually works on `@react-navigation/native-stack`?

### ISSUE THREAD

**Issue by Volper212** [react-navigation/react-navigation.github.io#1371]
https://github.com/react-navigation/react-navigation.github.io/blob/11192c45e473785c0738872a6caf644ff1c42f38/versioned_docs/version-6.x/preventing-going-back.md?plain=1#L97

For me, it works on an emulator on Android. In what environment does it not work? If it is iOS only, that should be mentioned.

**Comment by satya164** [comment]
It doesn't say that it doesn't work. It says it doesn't work properly. The specifics of when is not important and could change when code changes. So it's not recommended to rely on it on natie stack.
