### ISSUE TITLE
Stack Screen in a Drawer Navigator?

### ISSUE THREAD

**Issue by belcorro-apollo** [react-navigation/react-navigation.github.io#1379]
What is the behaviour of a Stack Screen in a Drawer Navigator? 

Seems like a typo to me.

![Image](https://github.com/user-attachments/assets/3c735df9-a184-4862-812c-bf94c8ac2666)

You can also see this in the version 6 documentation.

https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator

**Comment by satya164** [comment]
It's a typo. It'll behave like writing `Drawer.Screen` but types will be wrong.
