### ISSUE TITLE
Few typos in documentation

### ISSUE THREAD

**Issue by karthikvrao** [react-navigation/react-navigation.github.io#138]
I came across below typos in the documentation:
* Missing word 'to' in [react-navigation.github.io/docs/getting-started.md](https://github.com/react-navigation/react-navigation.github.io/blob/source/docs/getting-started.md)
`It should be enough for you know how to build ...`
* Missing word 'in' in [react-navigation.github.io/docs/headers.md](https://github.com/react-navigation/react-navigation.github.io/blob/source/docs/headers.md)
`Conveniently, these are the colors we're using our running example...`
* Misspelt word 'an' in [react-navigation.github.io/docs/contributing.md](https://github.com/react-navigation/react-navigation.github.io/blob/source/docs/contributing.md)
`Before submitting and issue...`

I will be happy to fix these in a single or separate PRs as deemed appropriate.

**Comment by vonovak** [comment]
closed through https://github.com/react-navigation/react-navigation.github.io/pull/144
