### ISSUE TITLE
Pause/Abort/Cancel a navigation action?

### ISSUE THREAD

**Issue by yingdongzhang** [react-navigation/react-navigation.github.io#141]
Say I have a form on a screen, and I want to warn the user if there are unsaved changes on the form when the user taps the Back button, the transition should be paused until the user takes an action, if the user chooses to discard the changes, resume the transition, otherwise abort the transition and stay on the same screen.
Is it possible? I know how to capture the `Navigation/BACK` action by listening to the `willBlur` event, but how can I pause/abort/cancel the navigation?

**Comment by vonovak** [comment]
please see https://reactnavigation.org/docs/routers.html#blocking-navigation-actions

**Comment by yingdongzhang** [comment]
@vonovak  Blocking! That's another same meaning word that I didn't think of, thank you!

**Comment by yingdongzhang** [comment]
@vonovak 

After reading the doc I'm still not quite sure about two things:
1. Where would you put that bit of logic? In the form component or in the reducer?
2. How do you pass the parameter such as `state.routes[state.index].params.isEditing` along with the goBack event?

**Comment by brentvatne** [comment]
> Where would you put that bit of logic? In the form component or in the reducer?

that logic would go on the reducer, same as in the code snippet from the docs.

> How do you pass the parameter such as state.routes[state.index].params.isEditing along with the goBack event?

i don't understand what this means, can you explain in more detail?

**Comment by yingdongzhang** [comment]
@brentvatne 

I was just wondering how to pass in the parameter such as `isEditing` in the example with the `NavigationActions.BACK` event, but I've figured it out. Thank you.

**Comment by brentvatne** [comment]
ah gotcha. thanks
