### ISSUE TITLE
Redux integration sample code

### ISSUE THREAD

**Issue by JChanceHud** [react-navigation/react-navigation.github.io#158]
The redux integration sample code now seems to be non-functional. Specifically the use of `addNavigationHelpers` in the last piece of source code no longer works:

```
import { addNavigationHelpers, NavigationActions } from "react-navigation";
```

`addNavigationHelpers` is no longer exported from the `react-navigation` package. I'm unsure if this is an intended change in `2.0` but it is undocumented and breaks previous code using this (`undefined is not a function`).

I'd be happy to submit a PR adding an export but based on the new warning added into the documentation it seems like this might be a discouraged strategy. Any thoughts about this would be appreciated, thanks.

**Comment by brentvatne** [comment]
hi! updated docs for this accordingly. thanks for pointing it out
