### ISSUE TITLE
Guide for using TypeScript with React Navigation

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#16]

**Comment by ctaggart** [comment]
The best thing I can find at the moment are the tests:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-navigation/react-navigation-tests.tsx

**Comment by jonolo6** [comment]
Typings for react-navigation is out of date for 2.*. AFAIK it is being worked on to be added into the actual react-navigation module. Here's an explained work-around until then: https://github.com/react-navigation/react-navigation/pull/4075#issuecomment-38984882. 

I.e. copy the contents in commend above into a file locally (to for instance `typings/react-navigation.d.ts`). Then update tsconfig.json to something like: 

```
....
"baseUrl": "./",
     "paths": {
         "react-navigation": ["typings/react-navigation.d.ts"]
     },
....
`

**Comment by mtford90** [comment]
No types for v3?

**Comment by eremzeit** [comment]
Following up in case someone is googling, are these the correct v3 types?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-navigation/index.d.ts

**Comment by brentvatne** [comment]
@eremzeit - yep.

**Comment by mtt87** [comment]
I'm using Typescript and everything works fine "out of the box" when it comes to the app but I'm unable to run any test with the default `react-test-renderer`.

I think it would be fantastic to get in the example project (which is written in TS) also an example on how to test it.
https://github.com/react-navigation/react-navigation/tree/master/example

At the moment I'm stuck with this issue and tried many things in the past couple of hours but unsuccessful 😢 
https://github.com/react-navigation/react-navigation/issues/5303

**Comment by brentvatne** [comment]
from @mtt87 on twitter:

> Actually it works fine in a new project with
npx react-native init MyTSProject --template react-native-template-typescript@6.3.7
>
> So it's a problem of my packages version probably.
>
> Thanks everyone for jumping in!

i believe this is the fix: witter.com/orta/status/1191400489176518664

> Random guess, but look if there are differences in the tsconfig file and maybe especially  allowSyntheticDefaultImports

**Comment by mtt87** [comment]
I'm planning to write down something in the next days to summarise what is needed in order to start testing and I will make a PR, ideally updating also the example so it's included there as well in the code.

Thanks @brentvatne

**Comment by satya164** [comment]
We've been using `babel-jest` and it works well. I suppose if you use `ts-jest` for typescript, it might require extra config. I'd recommend using `babel-jest` since that's closer to how metro compiles typescript.

Here is how we use it in stack repo: https://github.com/react-navigation/stack/blob/c10bd88d11a830a9a46978a03d4bbaa8934c0293/package.json#L85

**Comment by satya164** [comment]
Closing this because we already have guide for using React Navigation with TypeScript.

The testing part is not specific to React Navigation and should be in React Native docs/supported by default in `react-native` preset for jest.
