### ISSUE TITLE
Footer's `GitHub` link directs to a "naked" Github.com

### ISSUE THREAD

**Issue by fiber-god** [react-navigation/react-navigation.github.io#17]
I assume that the intended functionality was actually to link to the react-navigation repo, not GitHub itself. If so, I can submit a PR

**Comment by vojtechnovak** [comment]
Thanks for reporting, yes, that would be nice.

**Comment by vonovak** [comment]
Sorry, I commented from my phone which used a wrong account. But a problem
will be appreciated nevertheless :)
