### ISSUE TITLE
Docs: add example for reacting to focus / blur events when using getStateForAction

### ISSUE THREAD

**Issue by pensierinmusica** [react-navigation/react-navigation.github.io#171]
Hi!

Can we please include an example of https://github.com/react-navigation/react-navigation/issues/3893#issuecomment-390247914 in the docs here: https://github.com/react-navigation/react-navigation/issues/3893#issuecomment-390247914

Thanks!

**Comment by brentvatne** [comment]
hi, i don't understand the question. please create a new issue that describes in detail what you want to accomplish in concrete terms rather than implementation details

**Comment by pensierinmusica** [comment]
@brentvatne I was reporting this comment:

> react-navigation-redux-helpers@1.1.1 introduces a new export called createDidUpdateCallback that should fix this issue. Refer to the docs for how it's used.

Hence I think this section of the docs should be updated accordingly, to include an example:

https://github.com/react-navigation/react-navigation.github.io/blob/source/docs/redux-integration.md

Can you please re-open this issue? Thanks!

**Comment by ViktorJasch** [comment]
Hello. Are you find any solution for your problem? I have same trouble and "createDidUpdateCallback" does not help me.
