### ISSUE TITLE
Navigation options resolution links to wrong url

### ISSUE THREAD

**Issue by vikrantnegi** [react-navigation/react-navigation.github.io#172]
Hi,
When I open the docs though this [url](https://v2.reactnavigation.org/docs/en/common-mistakes.html) for [Common mistakes](https://v2.reactnavigation.org/docs/en/common-mistakes.html) there is wrong URL for Navigation options resolution at the end of documentation. It redirects us to an local host url for the page.

Please correct the url there.
Thanks.

**Comment by brentvatne** [comment]
hi there. I just changed v2.reactnavigation.org to redirect to reactnavigation.org, where this is resolved. when we release v3 it'll archive the current docs there. thanks!
