### ISSUE TITLE
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

### ISSUE THREAD

**Issue by Manoj002** [react-navigation/react-navigation.github.io#178]
Hello, 

Im trying to pass props to next screen through: 

    this.props.navigation.navigate('chat', { obj })

i have defined last as the lastscreen in app.js and obj is an object in my current component which i want to pass my next component.

I have also tried the pattern mentioned in document then too i guess im missing something.
Im new to react native as well to react navigation, can anyone help me out
Any help will be highly appreciated!!!

**Comment by Manoj002** [comment]
That was just a small mistake by my side, the way i was calling function got bit confused in es6

**Comment by evanlesmez** [comment]
I get the same warning even though my navigation still works. What was your fix?
