### ISSUE TITLE
Clarification around back button title config

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#190]
https://github.com/react-navigation/react-navigation/issues/2402#issuecomment-355150534

**Comment by leonelpena** [comment]
Based on my own confusion on how to use `headerBackTitle` and the examples posted by @lolobosse on his [comment](https://github.com/react-navigation/react-navigation/issues/2402#issuecomment-355150534) I have made some improvements to the documentation for `headerBackTitle` and `headerTruncatedBackTitle`: https://github.com/leonelpena/react-navigation.github.io/commit/a57c9536f58b4f81a3af60e0eedb505bfa7aeec8

@brentvatne do you think now is more clear? if so I will PR it...

**Comment by brentvatne** [comment]
yeah! looks good to me

**Comment by vonovak** [comment]
this is solved, so closing
