### ISSUE TITLE
tabBarLabel as function doesn't set label when using createMaterialBottomTabNavigator

### ISSUE THREAD

**Issue by sfreeman28** [react-navigation/react-navigation.github.io#195]
I just upgraded from using **createTabNavigator** to **createMaterialBottomTabNavigator** and now my tab labels no longer display. The labels are all empty (no text under icons) with my existing _tabBarLabel_ function.

Here it says I should still be able to use a function for tabBarLabel
https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#tabbarlabel

```
navigationOptions: ({ navigation }) => ({
    tabBarIcon: ({ focused, tintColor }) => {
        console.log('tabBarIcon') // this log is seen
        const { routeName } = navigation.state
        let iconName = 'default'
        if (routeName === ROUTE_NAME_COLLECTIONS) {
            iconName = 'grid'
        } else if (routeName === ROUTE_NAME_INFORMATION) {
            iconName = 'info'
	}
        return <SimpleLineIcons name={iconName} size={25} color={tintColor} />
    },
    tabBarLabel: () => {
        console.log('tabBarLabel') // this log is never seen
        const { routeName } = navigation.state
        let title = null
        if (routeName === ROUTE_NAME_COLLECTIONS) {
            title = strings.collections
        } else if (routeName === ROUTE_NAME_INFORMATION) {
            title = strings.info
        }
        return title
    },
    // tabBarLabel: 'Title', // this works when just setting string - but is not practical
}),
```

With my tabBarLabel function above I just always get empty labels and the log inside my function is never called.
If I set tabBarLabel to a static string then it does display, however I want different labels for each tab.
For completeness, if I do not supply a tabBarLabel property then my RouteName is displayed as the label text.

I am not setting `labeled: false`.
It feels as if when using **createMaterialBottomTabNavigator** _tabBarLabel_ cannot be a function.
Whereas my _tabBarIcon_ function is still working correctly.

When using **createTabNavigator** or **TabNavigator** this was working perfectly. I would get my labels showing and the function would run every time I change tab.

Any advice on whats going on here? Thanks

```
"react": "16.3.1",
"react-native": "0.55.4",
"react-navigation": "^2.3.1",
"react-navigation-material-bottom-tabs": "^0.2.0",
```

**Comment by brentvatne** [comment]
please provide a mcve (https://stackoverflow.com/help/mcve) on https://snack.expo.io or in a standalone github repo

**Comment by sfreeman28** [comment]
@brentvatne please see my snack here https://snack.expo.io/@sfreeman/materialtabs thanks!

**Comment by brentvatne** [comment]
cc @satya164

**Comment by satya164** [comment]
Confirmed that this is not supported. But don't think there's any reason to support it. There are no arguments to be passed here unlike other tab navigators where you get `focused` and `tintColor`.

> If I set tabBarLabel to a static string then it does display, however I want different labels for each tab.

Your `navigationOptions` is already a function. So you can return different labels for different routes already.

```js
navigationOptions: ({ navigation }) => {
  const { routeName } = navigation.state;

  let tabBarLabel;

  if (routeName === ROUTE_NAME_COLLECTIONS) {
    tabBarLabel = strings.collections;
  } else if (routeName === ROUTE_NAME_INFORMATION) {
    tabBarLabel = strings.info;
  }

  return {
    tabBarIcon: ({ focused, tintColor }) => {
    },
    tabBarLabel,
  };
};

```

**Comment by sfreeman28** [comment]
Thank you @satya164 @brentvatne for the help. That is definitely a valid solution to my use case.

Could we update the documentation to not mention setting a function here
https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#tabbarlabel

Many thanks

**Comment by vonovak** [comment]
@sfreeman28 the updated docs are live

**Comment by sfreeman28** [comment]
awesome thanks @vonovak

**Comment by razvantodea14** [comment]
It is possible to set a badge over a materialBottomNavigation tabIcon?
