### ISSUE TITLE
Error with overriding-shared-header-styles example

### ISSUE THREAD

**Issue by steve-prod** [react-navigation/react-navigation.github.io#20]
https://snack.expo.io/@react-navigation/custom-header-title-component
is the exact same as
https://snack.expo.io/@react-navigation/overriding-shared-header-styles

I believe https://snack.expo.io/@react-navigation/custom-header-title-component needs to be changed.

**Comment by brentvatne** [comment]
@steve-prod thank you for pointing this out! I have updated the custom-header-title-component example now
