### ISSUE TITLE
TransitionConfig documentation?

### ISSUE THREAD

**Issue by andrewcroce** [react-navigation/react-navigation.github.io#22]
Documentation for `transitionConfig` mentions:
> take a look at TransitionConfig in type definitions

The link to type definitions is dead. Where would I find a reference to the default `transitionsConfig`?

**Comment by brentvatne** [comment]
thanks. fixed the link. it now points to https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js

**Comment by andrewcroce** [comment]
Thanks 👍
