### ISSUE TITLE
Document whether setParams merges or replaces

### ISSUE THREAD

**Issue by LinusU** [react-navigation/react-navigation.github.io#229]
It would be nice to document whether the `setParams` function merges the object with the current params, or replaces the current params with the new object.

ref: https://reactnavigation.org/docs/en/navigation-prop.html#setparams-make-changes-to-route-params

**Comment by brentvatne** [comment]
good point! for anyone reading this before this change is made - it merges, like `setState`. if someone can submit a PR to add this to docs it'd be helpful!

**Comment by vonovak** [comment]
closing since this is already fixed - see the link in description

**Comment by brentvatne** [comment]
nice one @vonovak!
