### ISSUE TITLE
Stacks In Tabs Snack Sample is out of date (and may not work)

### ISSUE THREAD

**Issue by W7PEA** [react-navigation/react-navigation.github.io#234]
This sample: 
https://snack.expo.io/@react-navigation/stacks-in-tabs

From this page:
https://reactnavigation.org/docs/en/tab-based-navigation.html#a-stack-navigator-for-each-tab

Is out of date:
1. It does not use the proper component names (TabNavigator instead of createTabNavigator)
2. Its using "react-navigation": "1.0.0-beta.27"

I tried changing all those things restated the App (on Snack) the page flashes up and then I get an error:
Device: (146:59) undefined is not a function (evaluating '(0, _reactNavigation.createStackNavigator)({
  Home: { screen: HomeScreen },
  Details: { screen: DetailsScreen }
})')

NOTE: I was using SDK v27.0

Not sure what's wrong... but I could be Snacking (?) wrong.

**Comment by brentvatne** [comment]
thanks, fixed https://snack.expo.io/@react-navigation/stacks-in-tabs
