### ISSUE TITLE
Doc Translations

### ISSUE THREAD

**Issue by jorgeluisrezende** [react-navigation/react-navigation.github.io#235]
There is a doc explaining what i have to do to submit a translation?

**Comment by brentvatne** [comment]
there isn't currently, but if you'd like to get involved let me know your email address and what language you'd like to translate to and i can send you some instructions!

**Comment by jorgeluisrezende** [comment]
Oh great, my email is jorgeluisrezende94@gmail.com and i want to translate to brazilian portuguese

**Comment by brentvatne** [comment]
sent you an invite!

**Comment by seminelee** [comment]
Some have not been translated on the [Chinese website](https://reactnavigation.org/docs/zh-Hans/1.x/supported-react-native-versions.html). I'd like to support it if it is allowed.
My email is may.air@qq.com .
