### ISSUE TITLE
Guide to linking with hybrid iOS apps

### ISSUE THREAD

**Issue by James-E-Adams** [react-navigation/react-navigation.github.io#236]
Hi there!

Thanks for a great library :)

I found it a bit hard to stumble on how to get `react-navigation` working in a hybrid app. 

It just requires you adding the `RCTLinkingIOS` subspec in your `podfile` under React and running `pod install`, a la: https://github.com/react-navigation/react-navigation/issues/2977

Is there somewhere can document this? Happy to open a PR if someone could inform me where this sort of documentation should live!

Thanks

**Comment by brentvatne** [comment]
hi @James-E-Adams - wow I don't know how I missed this for so long. It does indeed require `RCTLinkingIOS` to be added - this is the default behavior when initializing a new project but I imagine in hybrid apps you may not opt-in to including it. A pull request for this is welcome! I also added a "Hacktoberfest" tag to this issue :P ([see more](https://hacktoberfest.digitalocean.com))

**Comment by James-E-Adams** [comment]
Nice! I just signed up for Hacktoberfest so I'll look at this tomorrow potentially? :)

**Comment by James-E-Adams** [comment]
Done. https://github.com/react-navigation/react-navigation.github.io/pull/259
