### ISSUE TITLE
Add links to some recent talks

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#246]
- https://www.youtube.com/watch?v=GBhdooVxX6Q - Mobile Navigation at React Alicante, an overview and comparison of the approaches taken by react-native-navigation and react-navigation
- https://www.youtube.com/watch?v=1LKqGx3z0W4 - Owning Transitions at React Native EU, a new transitioner API and how to use it
- https://www.youtube.com/watch?v=Z0Jl1KCWiag - It all starts with navigation at React Native EU, explains the evolution of React Native navigation libraries over time and the problems that required building native APIs to solve and what those solutions were.

**Comment by vonovak** [comment]
added in https://github.com/react-navigation/react-navigation.github.io/pull/248
