### ISSUE TITLE
DrawerNavigator don't re-render after changing redux state 

### ISSUE THREAD

**Issue by serzh-f** [react-navigation/react-navigation.github.io#250]
Hi. can you help me?

This is my DrawerNavigator

`    createDrawerNavigator(
        {
            Map: { screen: Map }
        },
        {
            contentComponent: props => <Sidebar {...props} />
        }
    )`

I have problem in <Sidebar> component which export with connect
`export default connect(mapStateToProps, bindAction)(Sidebar);`

I want to re-render my <Sidebar> component, when my redux state is changed. 
Component has <Switch> control.

**Comment by vonovak** [comment]
hi! it is hard to help with just the very short piece of code you shared. Since this is a usage question, I recommend you ask you your question on stackoverflow and include a minimal example of your problem (read here https://stackoverflow.com/help/mcve).
