### ISSUE TITLE
Tabs example snack uses deprecated TabNavigator

### ISSUE THREAD

**Issue by brettdh** [react-navigation/react-navigation.github.io#263]
The [Tab Navigation](https://reactnavigation.org/docs/en/tab-based-navigation.html) example links to this [basic-tabs](https://snack.expo.io/@react-navigation/basic-tabs) snack, which uses react-navigation 1.0.0-beta.27 and the now-deprecated `TabNavigator` function. This should be updated to link to a snack that runs the actual example code on that documentation page.

**Comment by brettdh** [comment]
Note: this appears to be the case for the other examples on that page as well.

**Comment by brentvatne** [comment]
thanks, fixed. feel free to create issues for any others that are outdated
