### ISSUE TITLE
2.18.0 documentation shows deprecated API

### ISSUE THREAD

**Issue by drakang4** [react-navigation/react-navigation.github.io#272]
![default](https://user-images.githubusercontent.com/11497500/47249827-77146700-d453-11e8-8da4-8ff8cf84e727.png)

All 2.18.0 guides and API documents uses deprecated API. It looks like this shows 1.5.13 version's documentation.

**Comment by drakang4** [comment]
![image](https://user-images.githubusercontent.com/11497500/47249947-f7879780-d454-11e8-9c5a-288df85606b2.png)

Also I found images return 404 not found.

**Comment by amhosseini** [comment]
Yes i have same problem, I want to read document about MaterialTopTabNavigator, but i received 404 error code that say not found.

**Comment by brentvatne** [comment]
i deployed the wrong version but it is fixed now
