### ISSUE TITLE
Document using Redux and Mobx in your app

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#280]
A common misconception of how we handled "redux integration" before was that this was how you used react-navigation in an app where you all use redux, when in fact it just demonstrated how to expose the guts of react-navigation to your redux store. Using redux, or any other state management library, is very easy to do alongside react-navigation -- you don't have to do anything different than you normally would. There are some tips we can provide around avoiding updates for inactive screens that may be handy though.

**Comment by gzzo** [comment]
Also a heads up related to this, there is a warning at the top of the [redux integration page](https://reactnavigation.org/docs/en/redux-integration.html) stating: 

> Warning: in the next major version of React Navigation, to be released in Fall 2018, we will no longer provide any information about how to integrate with Redux and it may cease to work.

Are you still planning on removing that page?  It's not clear if that documentation will work with 3.x

**Comment by brentvatne** [comment]
thanks for pointing that out @gzzo, I removed that page in https://github.com/react-navigation/react-navigation.github.io/commit/1909d9807026611d9783102cb6bb8ef21e68c4a6 and it'll go out in the next deploy
