### ISSUE TITLE
Changing Drawer label text for Drawer navigation

### ISSUE THREAD

**Issue by prudhvialahari** [react-navigation/react-navigation.github.io#289]
Hi,

I have a use case where I need to update the drawer label when a user changes the language of the application. There are two screens in the application, Home and Settings. When a user changes the language, I need to update the label with equivalent text in the respective language.  Here are the code snippets for the same,
1) App navigation:
```javascript
export default class AppNavigation extends React.Component {
  
  customDrawerNavigation = (props) => (
    <SafeAreaView style={{ flex: 1 }}>
      <View style={styles.LogoView}>
        <Image source={require('.././images/sample.jpg')} style={styles.LogoImage} />
      </View>
      <ScrollView>
        <DrawerItems {...props} />
      </ScrollView>
    </SafeAreaView>
  
  );
  render() {
    const DrawerStack = createDrawerNavigator({
      Home: HomePage,
      Settings: SettingsPage
    },
      {
        contentComponent: this.customDrawerNavigation,
        drawerPosition: 'left',
        initialRouteName: 'Home',
        drawerBackgroundColor: 'white',
        drawerWidth: 300
      }
    );
    return (
      <DrawerStack/>
    )
  }
}
```

2) Navigation options inside Home page: 
```javascript
 static navigationOptions = ({ navigation }) => {
        const {params = {}} = navigation.state;
        return {
            drawerLabel: params.leftMenuTitle,
            drawerIcon: () => (
                <Icon
                    name='home'
                    type='SimpleLineIcons'
                    size={22}
                    color='#4eaac4'
                />
            )
        }
    };

    componentDidMount() {
        this.props.navigation.setParams({
            leftMenuTitle: this.state.i18nProps["Navigation.Home"]
        });
    }
```

3) Navigation options inside Settings page:
```javascript
static navigationOptions = ({ navigation }) => {
        const { params = {} } = navigation.state;
        return {
            drawerLabel: params.leftMenuTitle,
            drawerIcon: () => (
                <Icon
                    name='settings'
                    type='MaterialIcons'
                    size={22}
                    color='#4eaac4'
                />
            )
        }
    };
    componentDidMount() {
        this.props.navigation.setParams({
            leftMenuTitle: this.state.i18nProps["Navigation.Settings"]
        });
    }
```

I'm maintaining the text value in the state. So, the only way to update the text on the UI is to use setState(). When a user changes the language, he will be on Settings page. So I can only update the state of settings page and thus I will be able to change the text for settings label on drawer navigation. 
My problem here is, I will not be able to change the drawer label for Home (Because I can't update the state of Home page unless it is mounted). The issue here is, settings label is in one language and Home label is in another language. The text of Home label is getting updated post navigating to Home page (Expected). 
So, anyone can help me out here?

**Comment by brentvatne** [comment]
you can use screenProps for this. we need to document this better in https://github.com/react-navigation/react-navigation.github.io/issues/45
