### ISSUE TITLE
Explain usage of createAppContainer

### ISSUE THREAD

**Issue by jkhusanov** [react-navigation/react-navigation.github.io#300]
Hey there, I would like to know where exactly do we need to put `createAppContainer`? Do we need to use it with each navigator? It was introduced in the recent version of react-navigation 3. Now we need to use the container directly. 

For my new app, I just wrapped my root navigator with it and placed in App.js, and it seems to be working and no problems with Redux so far. Thank you. 

More about App Container:  
https://reactnavigation.org/docs/en/app-containers.html#props-of-createappcontainer-on-react-native

`react-navigation: 3.0.0`

**Comment by brentvatne** [comment]
you only need to use it at the root of the app. cc @ericvicenti maybe you can clarify in doc

**Comment by brunokiafuka** [comment]
Hi, @brentvatne how do we do nested routing in `react-navigation: 3.0.0`, now that we have to use `createAppContainer `?

**Comment by MateusAndrade** [comment]
@jkhusanov  i used it after creating my stacks. On this way:

`
// Here is your app with all of your stacks together, even TabNavigator, etc.
const AppWithNavigationState = AppNavigator;

const AppContainer = createAppContainer(AppWithNavigationState);

class App extends PureComponent {
  render() {
    return (
      <AppContainer
          ref={(navigatorRef) => {
            NavigationService.setTopLevelNavigator(navigatorRef);
          }}
      />
    );
  }
}
` 
Then i just import this component on my main component. I dont know if this if the correct aproach, but it works fine for me.

**Comment by brentvatne** [comment]
@brunokiafuka - the app container is only at the very root of the app. it's a bit confusing i know, sorry :( think of it like a provider from redux and such

**Comment by munir0322** [comment]
I have mention my codes below. Anyone help how can i change AppContainer in root ?
mport {
    createStackNavigator,
    createSwitchNavigator,
    createBottomTabNavigator,
    createAppContainer
} from 'react-navigation';
import React, {
    Component
} from 'react';

import { NavigationService } from '../API/NavigationServices';

const AuthNavigator = createStackNavigator(
    {
      Login: {
        getScreen: () => require('./LoginScreen').default,
      },
    },
    {
      navigationOptions: {
        header: null,
      },
    },
  );

const TabNavigator = createBottomTabNavigator({
    Home: {
        getScreen: () => require('./HomeScreen').default,
    },
});

const MainNavigator = createStackNavigator({
    Tab: TabNavigator,
});

const AppNavigator = createSwitchNavigator({
    Splash: {
        getScreen: () => require('./SplashScreen').default,
    },
    Auth: AuthNavigator,
    Main: MainNavigator,
}, {
    initialRouteName: 'Splash',
}, );

//export to app.js

class Navigation extends Component {
    state = {};
    render() {
        return <AppNavigator ref={r => NavigationService.setTopLevelNavigator(r)} />
    }
}

export default Navigation;

**Comment by jaumetips** [comment]
//Its not working createBottomTabNavigator when i put inside the createAppContainer how can i solve this problema??? any example, full example with codes??


import React from 'react';
import {
  ActivityIndicator,
  AsyncStorage,
  StatusBar,
  StyleSheet,
  View,
  Text,
  YellowBox,
} from 'react-native';
import Icon from 'react-native-vector-icons/FontAwesome';
import { createStackNavigator, createSwitchNavigator,  createBottomTabNavigator, TabBarBottom, createAppContainer  } from 'react-navigation';
import Login from './components/src/screens/Login';



// To disable fucking yellowbox warnings
console.disableYellowBox = true


class AuthLoadingScreen extends React.Component {
  componentDidMount(){
     //SplashScreen.hide(); 
    
  }


  constructor() {
    super();
    this._bootstrapAsync();
  }

  // Fetch the token from storage then navigate to our appropriate place
  _bootstrapAsync = async () => {
    const userToken = await AsyncStorage.getItem('userToken');

    // This will switch to the App screen or Auth screen and this loading
    // screen will be unmounted and thrown away.
    this.props.navigation.navigate(userToken ? 'App' : 'Auth');
  };

  // Render any loading content that you like here
  render() {
    return (
      <View style={styles.container}>
        <ActivityIndicator />
        <StatusBar barStyle="default" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});




const AppStack = createStackNavigator({  
  MainGuest: MainGuest,
  Login:Login
});


const AuthStack = createStackNavigator({ Login: Login});



export default createAppContainer(createSwitchNavigator(
  {
    AuthLoading: AuthLoadingScreen,
    App: MainGuest2,
    Auth: AuthStack,
  },
  {
    initialRouteName: 'AuthLoading',
  }
));









const MainGuest2 = createBottomTabNavigator(
  {
    Home: { screen: HomeScreen },
    Settings: { screen: SettingsScreen },
    Profile: {screen:ProfileScreen}
  },
  {
    defaultNavigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;
        let iconName;
        if (routeName === 'Home') {
          iconName = `ios-information-circle${focused ? '' : '-outline'}`;
          return <Icon name="home" size={30} color="gray" />;
        } 
        else if (routeName === 'Settings') {
          iconName = `ios-options${focused ? '' : '-outline'}`;
          return <Icon name="comment" size={30} color="gray" />;
        }
        else if (routeName === 'Profile') {
          iconName = `ios-options${focused ? '' : '-outline'}`;
          return <Icon name="user" size={30} color="gray" />;
        }

        // You can return any component that you like here! We usually use an
        // icon component from react-native-vector-icons
        
      },
    }),
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    tabBarOptions: {
      activeTintColor: 'tomato',
      inactiveTintColor: 'gray',
      showLabel:false,
    },
    animationEnabled: true,
    swipeEnabled: true,
  }
);


class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Home!</Text>
      </View>
    );
  }
}

class SettingsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Settings!</Text>
      </View>
    );
  }
}

class ProfileScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Profile!</Text>
      </View>
    );
  }
}

**Comment by jaumetips** [comment]
> @jkhusanov i used it after creating my stacks. On this way:
> 
> `
> // Here is your app with all of your stacks together, even TabNavigator, etc.
> const AppWithNavigationState = AppNavigator;
> 
> const AppContainer = createAppContainer(AppWithNavigationState);
> 
> class App extends PureComponent {
> render() {
> return (
> <AppContainer
> ref={(navigatorRef) => {
> NavigationService.setTopLevelNavigator(navigatorRef);
> }}
> />
> );
> }
> }
> `
> Then i just import this component on my main component. I dont know if this if the correct aproach, but it works fine for me.

Can you put the full code of  -> const AppWithNavigationState = AppNavigator; ????

**Comment by MateusAndrade** [comment]
@jaumetips  i created the AppWithNavigationState with the following code:

`
const mainStack = createSwitchNavigator({
  [routes.YourRoute]: {
    screen: yourFirstStack,
  },
  [routes.YourTabContainer]: {
    screen: yourTabStack,
  },
}, {
  initialRouteName: routes.YourTabContainer,
  header: false,
});
`

I split my stacks on different files, by doing this i think you get a more clear file structure. Hope it helps: :)

**Comment by otaro808** [comment]
How can we use react-redux with react-navigation without react-navigation root component?
Use v2 only??

**Comment by brentvatne** [comment]
@otaro808 - `createAppContainer` returns a react component just like before

**Comment by brentvatne** [comment]
also that's literally right in the docs: https://reactnavigation.org/docs/en/app-containers.html

**Comment by brunokiafuka** [comment]
> @brunokiafuka - the app container is only at the very root of the app. it's a bit confusing i know, sorry :( think of it like a provider from redux and such

thanks @brentvatne, I've managed to make it work. Much appreciated.
