### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by ajchili** [react-navigation/react-navigation.github.io#302]
Referenced originally [here](https://github.com/react-navigation/react-navigation/issues/5254)

**Comment by brentvatne** [comment]
I'm not sure what's going on right now, there appear to be some issues with the domain but I am not the owner of it. We need @ericvicenti to look into this. I'm away in Thailand at the moment. You can access the docs for now by running them locally, see the instructions in the README: https://github.com/react-navigation/react-navigation.github.io

**Comment by vonovak** [comment]
fixed! :)
