### ISSUE TITLE
 inactiveColor not working

### ISSUE THREAD

**Issue by rameshmkll** [react-navigation/react-navigation.github.io#312]
Hi 
{
		initialRouteName: 'Home',
		activeColor: '#f0edf6',
		inactiveColor: '#000000',
		barStyle: { backgroundColor: '#694fad' },
	}.

not showing tabLabel when inactive.
is there any way show tab label when the tab is inactive.

**Comment by brentvatne** [comment]
I guess you mean 'inactiveTintColor' which is also under tabBarOptions: https://snack.expo.io/@notbrent/playful-cashew / https://reactnavigation.org/docs/en/bottom-tab-navigator.html#bottomtabnavigatorconfig

anyways if you need help this is not the right place, see https://reactnavigation.org/en/help.html
