### ISSUE TITLE
API Reference Section ERR_CONTENT_DECODING_FAILED in Chrome 

### ISSUE THREAD

**Issue by adamhaney** [react-navigation/react-navigation.github.io#322]
It appears that at some point in the last 24 hours (I was using it yesterday, December 11th 2018 it is now broken on December 12th 2018 ) the API reference section of has changed encodings in a way that breaks in Chrome. What does make this strange is that the link works in Safari (Version 12.0.1 (14606.2.104.1.1)). I'm guessing that some part of the deployment yesterday redeployed the docs and that there was an encoding error in the file that was uploaded? I am able to navigate to other parts of the website just not that specific page.

## Link to url in question
https://reactnavigation.org/docs/en/api-reference.html

## Chrome Error Message
```
This site can’t be reached The webpage at https://reactnavigation.org/docs/en/api-reference.html might be temporarily down or it may have moved permanently to a new web address.
ERR_CONTENT_DECODING_FAILED
```

I'm using Version 70.0.3538.110 (Official Build) (64-bit) of Chrome

**Comment by brentvatne** [comment]
the most recent deploy was 3 days ago, and this is hosted on github pages. this works for me right now, so it sounds like it could be an issue with your network

**Comment by brentvatne** [comment]
seems to happen sometimes to other github pages randomly: https://github.com/rust-lang/book/issues/709
