### ISSUE TITLE
Using react-navigation with state managers

### ISSUE THREAD

**Issue by MateusAndrade** [react-navigation/react-navigation.github.io#323]
I have worked on a project that used the version 2.3 of the library, and on this project we integrated the redux store with our navigation. 

After sometime i started a new project, with the version 3. of the react-navigation. Reading through the docs, i find that the is no problem if you dont need to attach the navigation to your store, and this is not 'supported' anymore.

Would be a problem, create my store, my reducers, actions etc and my navigation component. And then, to call another screen use something like: 

`export const redirectAuthenticateAccount = email => async () => {
  NavigationService.navigate(routes.AuthenticateAccount, { email });
};
`

My doubt is that it would cause some problems if a navigate through screen using this approach, and if needed call a dispatch to my actions?

**Comment by brentvatne** [comment]
hello there! this should not cause any problems as far as i can tell, but i didn't quite understand the last sentence, could you explain what you mean by "if needed call a dispatch to my actions?" and why this is making you doubt?

**Comment by MateusAndrade** [comment]
If i  use something like:

export const requestList = () => async (dispatch) => {
  // Here i dispatch my action to perform some changes on the store
  dispatch(requestFaqInfo());

  //Here i do a request to my amazing api
 const { payload } = await fetchContent();

 //Here, based on this change i call a navigate to some screen 
NavigationService.navigate(routes.AuthenticateAccount, { payload }); };
};

By doing this aproach, existe a possibilidade de ocorrer algum erro com minha store? 
is there any possibility of an error with my store? Because by performing a `dispatch(CallMyNavigateAction())`  for some reason, my store ends up being reset.

**Comment by brentvatne** [comment]
It'd be nice for this to demonstrate how to use Redux, Mobx, and React Context in a react-navigation project

**Comment by MateusAndrade** [comment]
@brentvatne If so, I can link to a project of mine that uses Redux and React-Navigation separately. Although the approach I chose is simple, it turns out to be a bit complex to try to use both libraries on the same project.

**Comment by brentvatne** [comment]
sure, what's the link to the project?

**Comment by MateusAndrade** [comment]
@brentvatne I was on vacation and I could not send the project link before, if it is still possible to link it, I would be happy to contribute. =)

Repo link: https://github.com/MateusAndrade/react-navigation-redux-example

**Comment by brentvatne** [comment]
we have a section on mobx state tree and on using redux (not to store navigation state but just for your app state):

https://reactnavigation.org/docs/en/redux-integration.html
https://reactnavigation.org/docs/en/MST-integration.html
