### ISSUE TITLE
Add docs for 'lazy' to createBottomTabNavigator and explain it more clearly

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#324]
Current doc in createTabNavigator may be confusing and perhaps lead people to think that the screen is unmounted when you switch away

**Comment by rgilbert1** [comment]
I'd love to improve the docs! This would be my first contribution to an open source project 😄what's the preferred process here, should I fork and open a PR with my proposed changes?

**Comment by brentvatne** [comment]
thanks @rgilbert1 !
