### ISSUE TITLE
React-Navigation SafeAreaView issues

### ISSUE THREAD

**Issue by Jaydip2711** [react-navigation/react-navigation.github.io#325]
When I used <SafeArewView> in </Header> tag it's working properly in iPhone X, XR, XS but when I show my app in iPhone SE, 6s, etc. it's not working. issues are when I used <SafeAreaView> it means that compatible in the only iOS notch device not other, but Here it's working in both types of device.

so how can I resolve this issues? also, I attach both device screenshot, u can see navigation bar difference in both device, it's not proper.

iPhone SE navigation bar bigger than actual

>>iPhone SE

![iphone SE](https://user-images.githubusercontent.com/29274771/50202796-42eef100-0385-11e9-9e56-965ad5a2725c.png)

iPhone XR
![iPhone XR - ](https://user-images.githubusercontent.com/29274771/50202839-6e71db80-0385-11e9-8b57-abeac7b96c7a.png)

**Comment by brentvatne** [comment]
update to the latest version of react-navigation and also issues are meant to be posted to https://github.com/react-navigation/react-navigation/issues and please follow the issue template :)
