### ISSUE TITLE
Please never change the documentation URLs

### ISSUE THREAD

**Issue by EyMaddis** [react-navigation/react-navigation.github.io#327]
Every time you update the version, you also migrate the website.
I would like to urge you to introduce immutable URLs for the documentation. 

There are a lot of places on the web where specific documentation is linked. Every time you update the website, you might break those links.

When you introduced v2, basically all links I visited pointed to 404.

This can be solved by having the version number in the URL, like this:
https://reactnavigation.org/docs/en/v3/navigation-actions.html

If you release a new version, just update the links on the homepage and point to v4.

Thanks.

**Comment by vonovak** [comment]
Hi and thanks for opening the issue. With the release of v3 we have switched the way we do versioning to the docusaurus built-in versioning system. That should solve the problem you describe. 

The way this works is that for old versions, the version number is indeed part of the urls. Urls that do not contain the version number always point to the docs for the latest stable version. You can visit docs for all version from here https://reactnavigation.org/en/versions.html

I assume the links you talk about are old links from eg. Stackoverflow with the `v1/v2` prefix(?). The fact they are broken is a pity, we should probably be able to do a redirect for those - cc @brentvatne

**Comment by EyMaddis** [comment]
> The way this works is that for old versions, the version number is indeed part of the urls. 
This is exactly the problem. When people share a link, it would point to a URL that might be invalid in a few months.

> Urls that do Urls that do not contain the version number always point to the docs for the latest stable version.

This should use a proper redirect to always have the latest version in the URL for the user. This solves the sharing issue for the future.

An example with broken links: https://hackernoon.com/getting-started-with-react-navigation-the-navigation-solution-for-react-native-ea3f4bd786a4

This links to StackNavigator via: https://reactnavigation.org/docs/navigators/stack

**Comment by brentvatne** [comment]
i'm not particularly interested in spending my own time on fixing these old links and as @vonovak mentioned, going forward this won't be an issue. if someone wants to add redirects for old urls then feel free to open a pr to do so
