### ISSUE TITLE
Navigation params returning old value for few seconds

### ISSUE THREAD

**Issue by st0495** [react-navigation/react-navigation.github.io#351]
When going from screen 1 to screen 2 I'm passing some parameter to screen 2 but when I navigate faster from screen 1 to screen2 & then back to screen 2 using navigation.goBack(), when I come back again to screen 2 then navigation params returns the old value for few seconds.

**Comment by brentvatne** [comment]
post to https://github.com/react-navigation/react-navigation and follow the issue template
