### ISSUE TITLE
navigationOptions for Navigator

### ISSUE THREAD

**Issue by lukasbalaz** [react-navigation/react-navigation.github.io#354]
According to https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html#renamed-navigationoptions-in-navigator-configuration you can configure `navigationOptions` for a navigator (and it works) but it's not mentioned in the docs https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig

**Comment by brentvatne** [comment]
it'd be repetitive to mention it in every navigator, but it does come up in the fundamentals section in 'configuring the header bar' - https://reactnavigation.org/docs/en/headers.html#sharing-common-navigationoptions-across-screens
