### ISSUE TITLE
Document enableURLHandling

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#373]
Useful to know prop on app container

**Comment by jarvisluong** [comment]
Could you tell me what is this feature and how can it bring any benefits? 🤔

**Comment by brentvatne** [comment]
as per https://reactnavigation.org/docs/en/deep-linking.html react-navigation handles deep links into your app by default. this isn't always desirable, and in v4 we are going to make it *not* do this by default. to disable automatic deep linking handling, you can pass `enableURLHandling={false}` to the app container

```jsx
const MyStack = createStackNavigator({ /* whatever */});
const Navigation = createAppContainer(MyStack);

export default class App extends React.Component {
  render() {
    return <Navigation enableURLHandling={false} />
  }
}
```
