### ISSUE TITLE
Explain how to use deep linking in nested navigators

### ISSUE THREAD

**Issue by benseitz** [react-navigation/react-navigation.github.io#387]
This issue [https://github.com/react-navigation/react-navigation/issues/1527#issuecomment-439201168](https://github.com/react-navigation/react-navigation/issues/1527#issuecomment-439201168) explains that you need to add an empty path string to all parent navigators, or else the deep link opens the app, but won't link to the correct screen.

Unfortunately this isn't mentioned in the docs :)

Can someone help me how this should be added to the [deep linking docs](https://reactnavigation.org/docs/en/deep-linking.html)?  I thought either at the end of the _Configuration_ paragraph or as a new menu item.

**Comment by brentvatne** [comment]
@benseitz - end of configuration section makes sense!

**Comment by benseitz** [comment]
@brentvatne I just forked and added this part to the documentations but am unsure if I should add it do the `docs/deep-linking.md` or `website/versioned_docs/version-3.x/deep-linking.md`?

**Comment by brentvatne** [comment]
both :)
