### ISSUE TITLE
Link to 'Screen Tracking for Analytics' page from 'Deep Linking' page is broken

### ISSUE THREAD

**Issue by trustyknave** [react-navigation/react-navigation.github.io#410]
---

### Current Behavior
When browsing the documentation, the button linking to the 'Screen Tracking for Analytics' page from the 'Deep Linking' page is broken – i.e. the button does not display the title of the next page ('Screen Tracking for Analytics') and clicking the button results in the 404 page rendering.

### Expected Behavior
- The button displays the title of the page instead of the default text ('next').
- Clicking the button renders the 'Screen Tracking for Analytics' page.

### How to reproduce
Go to the 'Deep Linking' page and click the 'next' button.

### Your Environment
Live version of the docs website.

**Comment by trustyknave** [comment]
Fixed in https://github.com/react-navigation/react-navigation.github.io/pull/411

**Comment by brentvatne** [comment]
thanks, landed this and released it
