### ISSUE TITLE
How to prevent pushing a screen twice when tapped quickly

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#42]
I think we need to still do more thinking about the right way to handle this in the library. Blocking a second action is wrong (hard to understand when you actually want to do this why it didn't work) and our current solution of using idempotent pushes (provide a key) isn't as ergonomic as it could be.

**Comment by vonovak** [comment]
this is no longer an issue in v2, imho (key is not needed), so closing.

**Comment by iamclaytonray** [comment]
@brentvatne @vonovak - could you provide a reason this is not an issue any longer, or a workaround? I still have this issue using the latest as of today. Thanks!

**Comment by vonovak** [comment]
@iamclaytonray please open a new issue with a repro if you're hitting an issue, thanks.

**Comment by brentvatne** [comment]
@iamclaytonray - `this.props.navigation.navigate` rather than `push`. https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html#navigateroutename-in-stacknavigator-is-less-pushy
