### ISSUE TITLE
how to support the translation?

### ISSUE THREAD

**Issue by seminelee** [react-navigation/react-navigation.github.io#440]
Some have not been translated on the [Chinese website](https://reactnavigation.org/docs/zh-Hans/1.x/supported-react-native-versions.html). I'd like to support it if it is allowed.

**Comment by brentvatne** [comment]
hello! absolutely, you can sign up as a translator here and submit your edits: https://crwd.in/react-navigation

**Comment by seminelee** [comment]
get!
