### ISSUE TITLE
How to get a reference to a navigator?

### ISSUE THREAD

**Issue by steinarsa** [react-navigation/react-navigation.github.io#443]
I just updated to version 3.11.0 from version 2.x.x. I used to be able to get a reference to a navigator by doing this:

```
<ModalStack
  ref={(navigatorRef) => {
     NavigationService.setModalNavigator(navigatorRef);
   }}
/>
```
but now this function never gets called. Is there still a way to implement something like this?

**Comment by brentvatne** [comment]
you need to call this on the navigator that is wrapped with `createAppContainer`

```
const ModalStack = createAppContainer(createStackNavigator({ A });

// later on
<ModalStack
  ref={(navigatorRef) => {
     NavigationService.setModalNavigator(navigatorRef);
   }}
/>
```
