### ISSUE TITLE
react-native0.59.9版本使用出现卡顿情况，打包后的应用也是如此。

### ISSUE THREAD

**Issue by mangoguang** [react-navigation/react-navigation.github.io#446]
我是使用react-native最新版本搭配的react-navigation,但是发现使用过程中出现页面非常卡顿的的情况，应用刚打开的时候，页面白屏，经过数十秒后才正常显示。然后点击进行路由切换的时候也是要十几秒甚至几十秒后页面才成功切换。晚上找的都是说关闭remote debug就正常了，但是我发现，我的是之后打开remote debug才是正常的，一旦关闭remote debug就很卡顿，打包成app后也是如此。

**Comment by ouzhou** [comment]
又不是中国人写的库，你写中文别人又看不懂，还要去翻译一遍，是不是对别人不尊重？
