### ISSUE TITLE
How to use i18n with react navigation

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#45]

**Comment by JulianKingman** [comment]
@brentvatne Any tips/pointers on how to do this without screenProps?

**Comment by brentvatne** [comment]
you could use context

**Comment by JulianKingman** [comment]
Sounds cool, how can navigation components make use of context (i.e. `navigationOptions`)?

**Comment by vonovak** [comment]
[context](https://reactjs.org/docs/context.html) is something react components have access to. So any component that you render in navigationOptions can use it. Typically, you would not use it directly but the i18n library in question would handle this.

**Comment by brentvatne** [comment]
here's an example: https://github.com/brentvatne/react-navigation-workshop-examples/blob/master/example/sections/Localization.js

need to turn this into a docs page

**Comment by bradbumbalough** [comment]
I believe this can be closed thanks to 4c73c8634e131c39156f4172d18544357a1ca23b 🎉.
