### ISSUE TITLE
在react16.8和react-native0.60.4版本中无法跳页

### ISSUE THREAD

**Issue by RubyKiss** [react-navigation/react-navigation.github.io#463]
跳页报错：instance.render is not a function . ( In 'instance.render()' ), instance.render is undefined

按照官方案例照抄进去爆报了这个错，不知道什么回事。

**Comment by eriveltonelias** [comment]
thanks for report the issue! 

and sorry for replying so late :/ 

I'll close this for now, since it not an issue anymore. let me know if you still need help.
