### ISSUE TITLE
Use collect name for `react-native-device-info`

### ISSUE THREAD

**Issue by chansuke** [react-navigation/react-navigation.github.io#471]
I was reading the document of [Supporting safe areas](https://reactnavigation.org/docs/en/handling-iphonex.html) part to fix android specific notch, but found that sample code in [here](https://reactnavigation.org/docs/en/handling-iphonex.html#android-notches) for `hasNotch()` API is probably not collect?

```
import { Platform } from 'react-native';
import { SafeAreaView } from 'react-navigation';
import DeviceInfo from 'react-native-device-info';

if (Platform.OS === 'android' && Device.hasNotch()) { //DeviceInfo.hasNotch()/ is collect?
  SafeAreaView.setStatusBarHeight(
    /* Some value for status bar height + notch height */
  );
}
```

source is [here](https://github.com/react-native-community/react-native-device-info#hasNotch)

**Comment by brentvatne** [comment]
repeating from the PR - you should use https://github.com/th3rdwave/react-native-safe-area-context instead.
