### ISSUE TITLE
Docs source for v4

### ISSUE THREAD

**Issue by freeworlder** [react-navigation/react-navigation.github.io#479]
Hi, i wanted to fix one error on the page drawer-navigator for v4,
but can't find it in source.
Page:
[https://reactnavigation.org/docs/en/drawer-navigator.html](https://reactnavigation.org/docs/en/drawer-navigator.html)
Source:
[https://github.com/react-navigation/react-navigation.github.io/edit/source/docs/drawer-navigator.md](https://github.com/react-navigation/react-navigation.github.io/edit/source/docs/drawer-navigator.md)

In the source it starts right away with RouteConfigs while the mistake i am talking about is in the upper part of the page, that i can't find in the source file. So, the question is where the source for it located?

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation.github.io/tree/source/website/versioned_docs/version-4.x
