### ISSUE TITLE
updating options with setoptions snack is down

### ISSUE THREAD

**Issue by codGmer** [react-navigation/react-navigation.github.io#581]
Hello,

The updating options with setoption snack is down, and I need to have it understand how to use this method correctly, i come from V3. This is the url:
https://reactnavigation.org/docs/en/next/headers.html#updating-options-with-setoptions and snack url: https://snack.expo.io/?platform=android&name=updating%20navigation%20options&dependencies=%40react-navigation%2Fcore%405.0.0-alpha.18%2C%40react-navigation%2Fnative%405.0.0-alpha.13%2C%40react-navigation%2Fstack%405.0.0-alpha.30%2C%40react-navigation%2Fbottom-tabs%405.0.0-alpha.16%2C%40react-navigation%2Fdrawer%405.0.0-alpha.17%2C%40react-native-community%2Fmasked-view%40%5E0.1.1%2Creact-native-safe-area-context%40~0.3.6%2Creact-native-safe-area-view%40%5E1.0.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2Fnext%2Fupdating-options-with-setparams.js

**Comment by jakub-gonet** [comment]
Sorry for the inconvenience, .js file with example was named differently than link we tried to create

Will be fixed by #582
