### ISSUE TITLE
useContext in the Authentication flows Guide

### ISSUE THREAD

**Issue by kockok** [react-navigation/react-navigation.github.io#596]
Following this guide, I got an error of unable to retrieve the `AuthContext`.

This problem is that, there's no way to export `const AuthContext = createContext(authContext);`

So, when I try to `useContext` in the SignIn component, there's no way to get the context.

Just wondering how to export the `AuthContext` inside a functional component.

**Comment by satya164** [comment]
```js
export const AuthContext = ...
```
https://exploringjs.com/es6/ch_modules.html

**Comment by kockok** [comment]
> ```js
> ```js
> export const AuthContext = ...
> ```
> 
> 
> https://exploringjs.com/es6/ch_modules.html
> ```

I know, but that would raise an error `'import' and 'export' may only appear at the top level (106:2)` just inside the functional component.

**Comment by satya164** [comment]
Sounds like you're creating the context inside a function. Don't create context in render. Move it to the top level.

**Comment by kockok** [comment]
> Sounds like you're creating the context inside a function. Don't create context in render. Move it to the top level.

When I export outside render, `export const AuthContext = React.createContext(null);`, I cannot get the values from `authContext = userMemo` so I initialized with null value.

However, When importing from the signIn component, there's an issue.
![Screenshot 2020-01-06 at 2 50 08 AM](https://user-images.githubusercontent.com/232541/71784517-4f48f900-302f-11ea-9b8e-c533b0c5c757.png)

**Comment by satya164** [comment]
That's because you don't have type annotations. You need to look up how to annotate context properly.

```js
React.createContext<Type | null>(null)
```

**Comment by Petercopter** [comment]
I think there was a misunderstanding about what the actual problem is. If you read the authentication flow documentation, it just loads all the AuthContext code into the App.js, and then the next step shows the signin page:
```
  const { signIn } = React.useContext(AuthContext);
```

There is no `AuthContext` to import, because nothing in the documentation exported it. I'm busy stumbling through setting up React Navigation 5 as well, so I would be curious about the answer as well, and then maybe we can update the documentation.

**Comment by Petercopter** [comment]
OK I see the problem. You need to create `AuthContext.js` and do something like
```
import { createContext } from 'react'

export const AuthContext = createContext()
```
Then you want to import that into your signin page.
