### ISSUE TITLE
Search bar doesn't indicate which version of the docs a search result corresponds to

### ISSUE THREAD

**Issue by shirakaba** [react-navigation/react-navigation.github.io#599]
When searching for documentation on the term "focused", there are two duplicate results for "Call a function when focused screen changes" – one corresponds to the `next` version of the docs, while the other corresponds to `4.x`. This lead me to unknowingly follow the wrong version of the docs.

In fact, the problem is not simply a complaint about duplicate search results – I was browsing version `4.x` of the docs and I clicked on the `useIsFocused` result, which pulled me out into the `next` version of the docs. It was only long after implementing my feature and finding that the code didn't work that I realised that I'd been redirected to an incompatible version of the docs.

![image](https://user-images.githubusercontent.com/14055146/71902323-ba8eea00-3159-11ea-87ab-dcef4f5048f5.png)

Suggested solution: I wouldn't want to the search to be hard-coded to search only the currently-browsed version of the docs, but if such an option could be toggled, it would be ideal. Either way, at the very least, it would be great if the corresponding version of the docs could be displayed beside each search result.

**Comment by eriveltonelias** [comment]
Hey @shirakaba 
thanks a lot for your feedback, we fixed this issue on our new docs.
