### ISSUE TITLE
Why the docs dir is empty

### ISSUE THREAD

**Issue by pranshuchittora** [react-navigation/react-navigation.github.io#634]
Hi there,
I tried to edit a doc by clicking on the `Edit` button, unfortunately I landed on a 404 page.

https://github.com/react-navigation/react-navigation.github.io/edit/source/docs/bottom-tab-navigator.md

Looking for some heads-up

**Comment by bell-steven** [comment]
Was about to create a PR, but it looks like it was already fixed in [this commit](https://github.com/react-navigation/react-navigation.github.io/commit/23899163fcad28b84cbb405c4ea901aebec516f2).

**Comment by eriveltonelias** [comment]
this PR should fix https://github.com/react-navigation/react-navigation.github.io/pull/657

thanks
