### ISSUE TITLE
Explain how to define/register routes in a way that is decoupled from the UI

### ISSUE THREAD

**Issue by arnoldbird** [react-navigation/react-navigation.github.io#65]
My related StackOverflow question is at https://stackoverflow.com/questions/48830648/how-to-define-a-route-and-then-create-a-simple-crosslink-to-that-route

How do I simply define/register a route such that I can call navigation.navigation('Someroute')?  And how do I do this without an approach like StackNavigator or TabNavigator that *also* impacts the UI?

Is it possible in React Navigation to simply load a screen (component) according to a route?

Thank you.

**Comment by arnoldbird** [comment]
The answer may be to create a custom navigator.  With a minimalistic custom navigator and a custom router, I then have a place to specify components for routes, and then I can use navigation.navigate(‘someRoute’).

**Comment by arnoldbird** [comment]
Returning to this task today, I just find it a little hard to believe I need to implement a custom navigator to accomplish the very simple task I am trying to accomplish:  add a button to a screen that, when tapped, transitions the user to another screen.  Is there a simple way to do this in React Navigation?  This does not appear to be documented.

**Comment by vonovak** [comment]
I'm afraid that what you're asking is not possible. You *do* need to register the routes somewhere before navigating to them. This static configuration will likely involve a StackNavigator or some other navigator which will handle things like going back to previous route, header appearance and more. This is different from from eg. react-router where you can just present any component (at least I think so).

**Comment by brentvatne** [comment]
@arnoldbird - what is a route to you aside from a binding from a name to a component, on a particular type of navigator? I think you need to define what a route is in your mind and describe a use case that is based in something that you will realistically do before we can discuss much further here

**Comment by arnoldbird** [comment]
I’m all set now.  I was confused about several different things simultaneously.   For one thing, I was a bit confused about the concept of a stack.  It helps if I think of a stack as a section of the app, in the sense that websites are often said to have sections.  React Navigation became very easy once I started using it exclusively and not trying to combine it with another library.
