### ISSUE TITLE
Documentation and Snack don't match for createBottomTabNavigator: tabPress

### ISSUE THREAD

**Issue by dantasfiles** [react-navigation/react-navigation.github.io#675]
For the `tabPress` section on `createBottomTabNavigator`, there are two versions for the same procedure.

[Documentation version](https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabpress) with `useEffect` hook:
```javascript
React.useEffect(() => {
  const unsubscribe = navigation.addListener('tabPress', e => {
    // Prevent default behavior
    e.preventDefault();
    // Do something manually
    // ...
  });
  return unsubscribe;
}, [navigation]);
```

[Snack version](https://snack.expo.io/?platform=android&name=createBottomTabNavigator%20%C2%B7%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%405.0.4%2C%40react-navigation%2Fbottom-tabs%405.0.4%2C%40react-navigation%2Fdrawer%405.0.4%2C%40react-navigation%2Fmaterial-bottom-tabs%405.0.4%2C%40react-navigation%2Fmaterial-top-tabs%405.0.4%2C%40react-navigation%2Fnative-stack%405.0.4%2C%40react-navigation%2Fstack%405.0.4%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fbottom-tab-prevent-default.js) linked to in above documentation:
```javascript
function HomeScreen({ navigation }) {
  navigation.addListener('tabPress', e => {
    // Prevent default behavior
    e.preventDefault();
    alert('Default behavior prevented');
    // Do something manually
    // ...
  });
  ...
```

I need to use this procedure but I don't know which is correct. Which is the correct version?

**Comment by satya164** [comment]
The snack version is incorrect

**Comment by dantasfiles** [comment]
@satya164 thanks so much for your time. I was able to use the documentation version successfully in my app.
