### ISSUE TITLE
Example on createMaterialBottomTabNavigator has incorrect tabBarIcon usage

### ISSUE THREAD

**Issue by Alanaktion** [react-navigation/react-navigation.github.io#678]
The [example](https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#example) on the documentation page for `createMaterialBottomTabNavigator` is not accurate. The page mentions above that `tabBarIcon` includes `focused` and `color` parameters, but does not include the `size` parameter that the `createBottomTabNavigator` does, so the icon sizes need to be explicitly set. Right now, the example passes `undefined` to the size prop on each of the `Ionicon` instances.

I'm not sure if there is an intention to eventually add a `size` param to this navigator at some point, but it seems like the documentation should explicitly set a size on the icons.

**Comment by eriveltonelias** [comment]
thanks for your issue report! fixed in here https://github.com/react-navigation/react-navigation.github.io/commit/3b115a18e36c6ce06fe51f492ffd9905e2bece2f
