### ISSUE TITLE
Title's translations don't work for Portuguese and Chinese

### ISSUE THREAD

**Issue by dudusotero** [react-navigation/react-navigation.github.io#682]
All titles on the website don't have a translation.
Is there a way to fix it? What can I do to help with it?

![image](https://user-images.githubusercontent.com/7073199/75204662-3a940200-5750-11ea-8eda-70afd2b35356.png)

![image](https://user-images.githubusercontent.com/7073199/75204670-4384d380-5750-11ea-8c7e-4696da8ae5d8.png)

**Comment by eriveltonelias** [comment]
Hey @dudusotero 

thanks for your report! we're improving our website and currently, the translations aren't ready yet but you can ping me on twitter and you can help us to translate to Portugese :)
