### ISSUE TITLE
Search results on older versions delivers wrong URL

### ISSUE THREAD

**Issue by amoutaux** [react-navigation/react-navigation.github.io#699]
Hello there, I'm having lots of trouble navigating through the docs when searching for elements not present in 5.x. It seems that the search box doesn't delivers the correct url.

**Steps to reproduce:**

- Select the correct documentation version (4.x for the following example)
- Search for a doc specific to an older version (at least for now), for example switch navigator
<img width="538" alt="Screenshot 2020-02-27 at 12 41 36" src="https://user-images.githubusercontent.com/54180928/75441850-b1064f00-595e-11ea-9ead-b75503e1d5f2.png">

**Observed:**

When clicking the result, the Page Not Found is displayed:

<img width="1143" alt="Screenshot 2020-02-27 at 12 37 17" src="https://user-images.githubusercontent.com/54180928/75441959-d5fac200-595e-11ea-8a04-4f3894c4a73c.png">

To fix it, one only needs to replace the 'en' with '4.x' in the url:

<img width="1154" alt="Screenshot 2020-02-27 at 12 37 44" src="https://user-images.githubusercontent.com/54180928/75442067-faef3500-595e-11ea-81f6-5a34b5b3c9b8.png">

I prefered starting a new issue since it looked different enough from #599 and #696

**Comment by rusakovic** [comment]
+ Please, check the link
https://reactnavigation.org/docs/en/native-stack-navigator.html

I found the link from search bar into your documentation.

**Comment by eriveltonelias** [comment]
thanks for your issue report! this was fixed.

**Comment by amoutaux** [comment]
I'm just seeing your response, thanks for that quick fix it's really appreciated !
