### ISSUE TITLE
Documentation for "Route prop reference" incorrect

### ISSUE THREAD

**Issue by myklosbotond** [react-navigation/react-navigation.github.io#701]
The docs page says

> Each screen component in your app is provided with the route prop automatically.

but in the code example the route is destructured from the navigation prop:

```jsx
function ProfileScreen({ navigation: { route } }) {
  return (
    <View>
      <Text>This is the profile screen of the app</Text>
      <Text>{route.params.name}</Text>
    </View>
  );
}
```

Shouldn't this be as follows?

```jsx
function ProfileScreen({ route }) {
 // ...
}
```

**Comment by eriveltonelias** [comment]
yes, thanks! 

fixed in here https://github.com/react-navigation/react-navigation.github.io/pull/703
