### ISSUE TITLE
Documentation links takes to latest version

### ISSUE THREAD

**Issue by jpaulomotta** [react-navigation/react-navigation.github.io#711]
First of all, thank you for your work on this amazing library. 

I'm experiencing an issue with the documentation as explained below.

**Current Behavior**
In the official docs, whenever you're viewing an old version, let's say: 3.x, the links inside the docs and on search always takes you to the latest version of the docs.

**Expected Behavior**

Links should stay consistent with the version we're viewing the docs at.

**How to reproduce**

Access https://reactnavigation.org/docs/3.x/bottom-tab-navigator/

Click on the first link ```For a complete usage guide please visit _Tab Navigation_```. 

It links to https://reactnavigation.org/docs/tab-based-navigation/ instead of https://reactnavigation.org/docs/3.x/tab-based-navigation/.

Same issue on the search bar and every other link inside the docs, except the sidebar which links correctly between versions.

**Search bar example**
On 3.x docs search for Header. Every link there takes you to the latest version of the documentation.

![Screen Shot 2020-03-04 at 11 52 53 AM](https://user-images.githubusercontent.com/1813007/75891763-03d48080-5e0f-11ea-9b64-364f69bc6bda.png)

Ideally, the links inside the docs should keep the version number consistent.

**Comment by eriveltonelias** [comment]
thanks @WoLewicki, I'll check it.

**Comment by eriveltonelias** [comment]
fixed :D

**Comment by jpaulomotta** [comment]
Thanks. The search links have been fixed.

But inner links are still broken:

https://reactnavigation.org/docs/3.x/bottom-tab-navigator/
![Screen Shot 2020-03-06 at 3 38 12 PM](https://user-images.githubusercontent.com/1813007/76112243-99634200-5fc0-11ea-8a68-6889bbc01517.png)
Clicking on "Tab Navigation"

Takes you to 5.x docs:
![Screen Shot 2020-03-06 at 3 38 26 PM](https://user-images.githubusercontent.com/1813007/76112281-aaac4e80-5fc0-11ea-9edb-34138657e096.png)
