### ISSUE TITLE
Documentation for header bar - Dead links

### ISSUE THREAD

**Issue by jeremyhallden** [react-navigation/react-navigation.github.io#714]
- Go to https://reactnavigation.org/docs/headers/
- Links to 
https://reactnavigation.org/docs/headers/stack-navigator.html#navigationoptions-used-by-stacknavigator
exist in two places. These links do not work - "Page Not Found". The links are "in the API reference" and "reference"

(I hope that this is the right place for registering documentation issues)

**Comment by eriveltonelias** [comment]
Hey @jeremyhallden 

thanks for your report! Can you check again ? because I'm not finding this link in "API reference"

**Comment by jeremyhallden** [comment]
No, the link texts on this page are  "in the API reference" and "reference"

**Comment by jeremyhallden** [comment]
![Screenshot_20200306-135807](https://user-images.githubusercontent.com/6299617/76085555-8f3a4700-5fb2-11ea-8cf7-c51d3cbb4233.jpg)

**Comment by eriveltonelias** [comment]
thanks! fixed.
