### ISSUE TITLE
Documentation on navigating to a nested screen and rendering screens in the path.

### ISSUE THREAD

**Issue by compojoom** [react-navigation/react-navigation.github.io#731]
The nesting navigators docs: https://reactnavigation.org/docs/nesting-navigators
explain how to navigate from NavigatorA to a screenB2 in NavigatorB.

However as it is apparent from this issue: https://github.com/react-navigation/react-navigation/issues/7698 people don't understand how to navigate from NavigatorA to NavigatorB and render screenB1 and then screenB2. This way one could have a back button. 

Right now ScreenB2 is rendered and there is no back button which feels strange. The suggested workaround in the above issue kind of work, but they feel like a hack (set timeout with push)

Is there any recommended approach for this? If yes we should add it to the nesting navigators docs as it seems a common thing to do.

**Comment by vostvesh** [comment]
I faced the same issue. And it helped me to install headerMode="none" in the parent Navigator

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator
