### ISSUE TITLE
Broken link in docs/4.x/navigation-views/#transitioner

### ISSUE THREAD

**Issue by jay-jlm** [react-navigation/react-navigation.github.io#735]
Link to https://reactnavigation.org/docs/4.x/navigation-views/transitioner.md is currently a 404

**Comment by eriveltonelias** [comment]
Hey @jay-jlm 

where did you find the reference for this link?

**Comment by jay-jlm** [comment]
The link is in the issue titie ☝️

**Comment by AM-77** [comment]
The reference is in the [Navigation views](https://reactnavigation.org/docs/4.x/navigation-views/) page in the Transitioner section

**Comment by eriveltonelias** [comment]
thanks! fixed in here https://github.com/react-navigation/react-navigation.github.io/commit/21c7d6aa6744657d2b92242e5c39ef61df220c32

for more info: https://reactnavigation.org/docs/4.x/upgrading-from-3.x/#removal-of-transitioner
