### ISSUE TITLE
accessing focused prop with tabBarButton

### ISSUE THREAD

**Issue by wrightmk** [react-navigation/react-navigation.github.io#743]
Is there a non hacky way to access the focused prop in createBottomTabNavigator's tabBarButton  method? (Similar to how tabBarIcon and tabBarLabel have access to it)

**Comment by jarvisluong** [comment]
Hi! @wrightmk , I believe that tabBarButton doesn't provide the focused prop just yet. @satya164 should this be something to add to the current bottom tab?

**Comment by satya164** [comment]
I'm not sure the touchable should know the focused state, but there's already `accessibilityStates` prop, and can use `useIsFocused` hook to get that status if needed.

**Comment by felire** [comment]
This works for me: 

```
  tabBarIcon: ({ focused }: { focused: boolean }) => <TabBarIcon route={route.name} focused={focused} />,
  tabBarButton: ({ children, ...rest }) => {
    return (
      <TouchableOpacity {...rest} onPress={() => whatever>
        {children}
      </TouchableOpacity>
    );
  },
  ```

**Comment by cglacet** [comment]
@felire `children` is a props like any other so you could write:

```
  tabBarButton: (props: BottomTabBarButtonProps) => <TouchableOpacity {...props} onPress={() => whatever} />,
  ```
  
  I wonder why this isn't properly documented. Anyway, thanks for the info 👍

**Comment by ddikodroid** [comment]
> **tabBarButton: props => <TabBarCustomButton {...props} color={props.accessibilityState.selected ? GLOBAL.COLOR_REPUBLICAN_CHECKED :GLOBAL.COLOR_WHITE_GRAY } />**,
> 
> Yes, you are right this **fosued** property does not work with tabBarButton.In replacement we can use accessibilityState.selected. It will work you.


```ts
'props.accessibilityState' is possibly 'undefined'.
```

**Comment by jessepinho** [comment]
Just came across [`useIsFocused`](https://reactnavigation.org/docs/use-is-focused/), which solves this problem from inside the `tabBarButton` component :)
