### ISSUE TITLE
Broken links.

### ISSUE THREAD

**Issue by AM-77** [react-navigation/react-navigation.github.io#744]
Page: https://reactnavigation.org/docs/header-button
File: versioned_docs/version-5.x/header-buttons.md (in line 82 and 88) 

Links: 
1- [headerBackImage] stack-navigator.html#headerbackimage . in [Customizing the back button](https://reactnavigation.org/docs/header-buttons/#customizing-the-back-button)

2- [api reference] stack-navigator.html#headerleft, in [Overriding the back button](https://reactnavigation.org/docs/header-buttons/#overriding-the-back-button)

I think you need just to replace .html with .md

**Comment by jarvisluong** [comment]
Thanks for the report! Would you submit a PR for this?

**Comment by cmcodes1** [comment]
@jarvisluong I have submitted a PR (#759) to fix this issue.

**Comment by cmcodes1** [comment]
@jarvisluong I have submitted another PR (#760) to fix the second broken link of this issue.

**Comment by cmcodes1** [comment]
@AM-77 You can close this issue now! :)
