### ISSUE TITLE
[5.x] No documentation on options or screenOptions (which both have a very loose generic type, ScreenOptions)

### ISSUE THREAD

**Issue by shirakaba** [react-navigation/react-navigation.github.io#757]
The 5.x docs don't give me any information on what `options` are supported on `Stack.Screen` nor what `screenOptions` are supported on `Stack.Navigator`.

Looking in the typings of  `@react-navigation/core/lib/typescript/src/types.d.ts` in `@react-navigation/core@5.3.4`, the `ScreenOptions` typings are completely non-descriptive.

In each occurrence across the typings, ScreenOptions is defined as a generic (`ScreenOptions extends object` or `ScreenOptions extends object = {}`), which doesn't give any information on what `options` are supported on `Stack.Screen` or what `screenOptions` are supported on `Stack.Navigator`.

Related:
* #7855

**Comment by ayushpattnaik** [comment]
https://reactnavigation.org/docs/screen-options

Refer this link

**Comment by shirakaba** [comment]
@ayushpattnaik That page just says "there are screen options". It doesn't say *what* all those screen options are.

e.g. Is `banana` an option? What range of values might it take? We'll never know.

**Comment by satya164** [comment]
Options depend on the navigator and are document on the navigator's page https://reactnavigation.org/docs/stack-navigator#options
