### ISSUE TITLE
Is HeaderHeightContext a stable API?

### ISSUE THREAD

**Issue by superguineapig** [react-navigation/react-navigation.github.io#758]
First, wow! Been using ReactNavigation since v3. It just keeps getting better. Thanks to everyone for making this thing so awesome!

Anyhow, I noticed exports for:

`HeaderHeightContext` https://github.com/react-navigation/react-navigation/blob/2467ce4ff7dcd234280863ca0a767691b3b77d42/packages/stack/src/index.tsx#L41 

and the corresponding effect `useHeaderHeight` https://github.com/react-navigation/react-navigation/blob/2467ce4ff7dcd234280863ca0a767691b3b77d42/packages/stack/src/index.tsx#L45

in Stack (v5)

I'd love to use them but haven't seen them documented on the site yet.

Question: are these things that I can start using in production code, or are they undocumented for a reason? e.g. experimental, pre-release, etc.

Thanks again!

**Comment by cseelus** [comment]
See here https://reactnavigation.org/docs/stack-navigator/#headertransparent

**Comment by superguineapig** [comment]
Oh nice. Thanks for pointing that out @cseelus
