### ISSUE TITLE
Undefined State on Root react-navigation 5

### ISSUE THREAD

**Issue by felire** [react-navigation/react-navigation.github.io#761]
**Current Behavior**

I'm running the next code:

```
const getActiveRouteName = state => {
  const route = state.routes[state.index];

  if (route.state) {
    // Dive into nested navigators
    return getActiveRouteName(route.state);
  }

  return route.name;
};

const AppNavigator = () => {
  const routeNameRef = useRef();
  const navigationRef = useRef();
  useEffect(() => {
    const state = navigationRef.current.getRootState();

    // Save the initial route name
    routeNameRef.current = getActiveRouteName(state);
  }, []);

  // const statusBarProps = statusBarStyles[getCurrentRouteName(state)] || statusBarStyles.default;

  return (
    <NavigationContainer
      ref={navigationRef}
      onStateChange={state => {
        const previousRouteName = routeNameRef.current;
        const currentRouteName = getActiveRouteName(state);

        if (previousRouteName !== currentRouteName) {
          // The line below uses the @react-native-firebase/analytics tracker
          // Change this line to use another Mobile analytics SDK
          // analytics().setCurrentScreen(currentRouteName, currentRouteName);
          console.tron.log('log analytics');
        }

        // Save the current route name for later comparision
        routeNameRef.current = currentRouteName;
      }}>
      {/* <StatusBar animated {...statusBarProps} /> */}
      <Navigator />
    </NavigationContainer>
  );
};

export default AppNavigator;
```
The problem is that in the `useEffect` after execute `getRootState` the state is undefined, the `getRootState` is returning undefined and the app crash later because is trying to access to the routes os the state.

**Expected Behavior**

- What do you expect should be happening?
- I expect setting the name of the first screen or at least log it

**How to reproduce**

- Follow the docs of how to configure analytics in react-navigation 5, in that place you have all the code: [https://reactnavigation.org/docs/screen-tracking/](https://reactnavigation.org/docs/screen-tracking/)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                |  Both
| @react-navigation/native |      5.1.6
| react-native                  | 0.62.2
| expo                           |
| node                           |
| npm or yarn               |     yarn

**Comment by eriveltonelias** [comment]
Hey @felire! thanks for your report! 

I just copied the code from here https://reactnavigation.org/docs/screen-tracking/#example and seems working fine, so on initial state and no navigator, so state will be undefined. Just add a condition before checking `state.routes` to make sure `state` is not undefined
