### ISSUE TITLE
Expo examples failing

### ISSUE THREAD

**Issue by carinlynchin** [react-navigation/react-navigation.github.io#775]
https://reactnavigation.org/docs/status-bar/

none of the expo links are working and getting error "Unable to resolve module 'module://react-native-safe-area-view.js'

**Comment by WoLewicki** [comment]
There should pop an option in the bottom-left corner to add this module to package.json. If it doesn't, just add `"react-native-safe-area-view": "1.1.1"` to package.json by yourself. It happens because this module is not added to the snack by default. Does it solve your issue?

**Comment by eriveltonelias** [comment]
thanks @WoLewicki! 

let us know if you still need help.
