### ISSUE TITLE
Unable to load target module react-navigation/native

### ISSUE THREAD

**Issue by stefan0905** [react-navigation/react-navigation.github.io#780]
I have a problem with my app that it doesn't start anymore after adding the react-navigation packages. In order to fix my issue I decided to try it out on a new app and followed the documentation of [the getting started page](https://reactnavigation.org/docs/getting-started) And after doing that and starting the app I still get the same issue.
![failure](https://user-images.githubusercontent.com/56909023/82058326-dfc1d500-96c4-11ea-9e81-9cf65e7447f9.jpg)

**Comment by eriveltonelias** [comment]
Hey @stefan0905,

make sure to install `@react-navigation/native` like mentioned on the docs https://reactnavigation.org/docs/getting-started/#installation
