### ISSUE TITLE
Add createNativeStackNavigator docs page

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#794]
For now it can just link out to https://github.com/software-mansion/react-native-screens/tree/master/native-stack

**Comment by saideepesh000** [comment]
@brentvatne, Can I work on this, and also should I need to add the "Try this on Snack" examples whenever necessary , so that I can learn and contribute simultaneously 😅

**Comment by saideepesh000** [comment]
@brentvatne, @satya164 but it's already present on the site.

![Screenshot (279)](https://user-images.githubusercontent.com/43727167/97398422-3b99b680-1911-11eb-8348-ed236d6084e2.png)

**Comment by brentvatne** [comment]
yeah i just added that recently, i guess we can close this issue :)
