### ISSUE TITLE
Help links in documentation point to wrong locations

### ISSUE THREAD

**Issue by Delph** [react-navigation/react-navigation.github.io#799]
On this page: https://reactnavigation.org/help/
The link to "post an issue" points to feature request creation on Canny
The link to "create a feature request on Canny" points to #react-navigation on Reactiflux Discord.

**Comment by eriveltonelias** [comment]
thanks! fixed in here https://github.com/react-navigation/react-navigation.github.io/commit/ae90b40fac4a57f473a41b9436a5bcea16ee9981
