### ISSUE TITLE
TypeError: TaskQueue: Error with task : Cannot read property 'measureInWindow' of undefined

### ISSUE THREAD

**Issue by akhilsanker** [react-navigation/react-navigation.github.io#804]
Getting this error while running on android device.

Environment:
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-navigation": "^2.18.3"

any solution

**Comment by eriveltonelias** [comment]
Hey @akhilsanker, you're using a too old version of react-navigation... please try to upgrade to the latest version and let me know if you still need help.
