### ISSUE TITLE
what is difference bewteen jumpto and navigate  in tab 

### ISSUE THREAD

**Issue by alirezarastegarfard** [react-navigation/react-navigation.github.io#820]
<Button
                title="Go to profile"
                onPress={() => navigation.jumpTo('Profile', { owner: 'Michaś' })}
            />
or 

   <Button
                title="Go to profile"
                onPress={() => navigation.navigate('Profile', { owner: 'Michaś' })}
            />

**Comment by SleeplessByte** [comment]
I believe `navigate` is a common action that traverses nested navigators and `jumpTo` is specifically for the _current_ navigator *only*.

**Comment by brentvatne** [comment]
the effect will be the same if you have a tab by the name Profile. but if you don't, and you have a parent navigator with a route by the name Profile, then navigate will switch to that but jumpTo will not. jumpTo is only handled by tab navigators.
