### ISSUE TITLE
Explain that tabNavigators inherit stackNavigator behaviour.

### ISSUE THREAD

**Issue by scucchiero** [react-navigation/react-navigation.github.io#824]
Missing some info about tabNavigators, specially bottomTabNavigators.
I'm not sure if it wraps a stackNavigator but they inherit most of its APIs.
However, that is not being displayed on the docs.

https://reactnavigation.org/docs/bottom-tab-navigator/

**Comment by brentvatne** [comment]
this happens with every navigator and is documented here: https://reactnavigation.org/docs/nesting-navigators#navigator-specific-methods-are-available-in-the-navigators-nested-inside
