### ISSUE TITLE
The repo of the web example please

### ISSUE THREAD

**Issue by yairopro** [react-navigation/react-navigation.github.io#854]
What's the repo of the [web example](https://react-navigation-example.netlify.app/) used for the blog post [_React Navigation on the Web_ ](https://reactnavigation.org/blog/2020/05/16/web-support/).

It would be great to add the link to the repo in the documentation or at least to the blog post itself.

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/tree/main/example

**Comment by yairopro** [comment]
thanks
