### ISSUE TITLE
MobX Integration

### ISSUE THREAD

**Issue by sidferreira** [react-navigation/react-navigation.github.io#86]
There's this gist I just shared. It's based on a running project I'm working on.

https://gist.github.com/sidferreira/72e17d29b224ca93cf86901ed1ceb032

Feel free to link or copy.
In any way, a mention will be acceptable

Suggestions are welcome

ps: I still tweaking it, so, if you prefer, I can beep when I feel it a bit more "done"

**Comment by llamaluvr** [comment]
Please do keep us posted. I keep putting off upgrading to post-beta-27 because everything is very different and the documentation is much more redux-centric. Appreciate you sharing this!

**Comment by sidferreira** [comment]
@llamaluvr Is it too different than 1.4?

**Comment by brentvatne** [comment]
a pr would be welcome for this!
