### ISSUE TITLE
Why exactly shouldn't I use useLinking?

### ISSUE THREAD

**Issue by spacesuitdiver** [react-navigation/react-navigation.github.io#874]
For us `Linking.getInitialPath()` is not enough. We treat pathed routes as first class citizens and the initial route of the app can be navigated to a few different ways.

1. Linking.getInitialPath();
2. App launch might lead us to something like /users/abc123 
3. We might persist the last location of the user in redux
4. Push notifications might have an href

[Docs](url) state:
> You should use the linking prop on NavigationContainer instead of using this hook directly. This documentation exists for users who were already using this hook before the linking prop was added.

But why? It seems like using the useLinking and initialState prop is a perfect way to control the initial state/route of your navigation tree.

**Comment by satya164** [comment]
Why doesn't the `linking` prop and `initialState` prop on the `NavigationContainer` work for your use case?

**Comment by spacesuitdiver** [comment]
It does just missed that in the docs. We ended up with all sorts of other issues with sibling morals and deep linking though that I might try to raise another issue about but for now we are just going to link manually unfortunately. Thanks.
