### ISSUE TITLE
Typo in Documentation 

### ISSUE THREAD

**Issue by TechSaq** [react-navigation/react-navigation.github.io#918]
https://reactnavigation.org/blog/2020/05/16/web-support/

It has typo under **Permanent Drawer** section:

**Current:** 
Another way we can make maximum **us** of the available screen size **is** by making our 

**Changes:**
Another way we can make maximum _use_ of the available screen size by making our 

**Please assign this issue to me.**

![image](https://user-images.githubusercontent.com/28209930/103744776-5a5cad80-5024-11eb-8ec8-e0e9e07c465f.png)

**Comment by bnainar** [comment]
Do it
