### ISSUE TITLE
Support multilingual documentation

### ISSUE THREAD

**Issue by kyo504** [react-navigation/react-navigation.github.io#93]
Is there any plan to support multilingual for the website? I guess it'd be very useful if we do.

**Comment by brentvatne** [comment]
yeah I would like to do this but haven't had time. will circle back to it after we get react-navigation@2.0 released!

**Comment by kyo504** [comment]
Thanks. I'm looking forward to having a change to contribute on this later. :)

**Comment by vonovak** [comment]
Closing since we have this
