### ISSUE TITLE
goBack reference use of keys is confusing

### ISSUE THREAD

**Issue by wolfhog** [react-navigation/react-navigation.github.io#94]
Hi, I noticed a discrepancy between the documentation and implementation of keys used for navigation, for example in the case of navigating backwards from a specific screen in the stack using goBack(key). The documentation, especially the code examples, make it seem like the key is the route name, however this is not the case and does not work. The documentation should be updated to reflect this, currently it is very misleading and the code examples provided do not work in practice.

**Comment by brentvatne** [comment]
can you point me to exactly what sections / code are confusing to you from the docs?

**Comment by crazymao** [comment]
For example in this section: [goBack - Close the active screen and move back](https://reactnavigation.org/docs/navigation-prop.html#goback-close-the-active-screen-and-move-back) the code example states that you can do `goBack('screen-123')` to go back from screen-123, implying to use the screen name as the key, which is not how the API works, in other works this and many other code examples do not work in practice.

**Comment by brentvatne** [comment]
thanks for pointing that out! indeed we should be clear that the string that is passed in there should be a key.

let me know if you find other examples of code that are confusing or don't work as you'd expected and send me a link to them, thanks!

**Comment by brentvatne** [comment]
related: https://github.com/react-navigation/react-navigation.github.io/issues/50
