### ISSUE TITLE
Correct NativeAnimatedHelper in Testing with Jest dock

### ISSUE THREAD

**Issue by christian-hess-invillia-tembici** [react-navigation/react-navigation.github.io#970]
I noticed that the mock path for NativeAnimatedHelper is wrong. Aparrently there is no "src" folder in the path anymore.
I've created a PR for review:
https://github.com/react-navigation/react-navigation.github.io/pull/969

**Comment by eriveltonelias** [comment]
thanks! fixed in here https://github.com/react-navigation/react-navigation.github.io/commit/2538d5e54940996955ae49bf5e82d02db74f5025
