### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by mnightingale** [react-navigation/react-navigation.github.io#973]
When you click the "See all 150 results" it takes you to https://reactnavigation.org/search?q=route
But it always displays "No results were found"

**Comment by swrobel** [comment]
Still occurring, ex: https://reactnavigation.org/search?q=navigation
<img width="1422" alt="Screen Shot 2021-06-18 at 3 43 40 PM" src="https://user-images.githubusercontent.com/157270/122621966-07b00480-d04c-11eb-8cd3-8d201ed65b3f.png">
