### ISSUE TITLE
Documentation needs to be updated to install @react-native/stack

### ISSUE THREAD

**Issue by ADRE9** [react-navigation/react-navigation.github.io#984]
Without installing the @react-native/stack we get an error
Unable to resolve module @react-navigation/stack from E:\user\PROJECTS\React Native\project\App.js: @react-navigation/stack could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
`import * as React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';`

Only solution is to install @react-native/stack by using `yarn add @react-native/stack`
Rest all solutions failed.

**Comment by kpose** [comment]
@ADRE9 As expected, stack navigator needs to be installed before it could be used, please follow the installation guide here https://reactnavigation.org/docs/stack-navigator#installation for more information
